# app.yaml

env: standard
runtime: nodejs16

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\l
    upload: build/.*\.(json|ico|js)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
